// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainticketBooking.Data;

#nullable disable

namespace TrainticketBooking.Migrations
{
    [DbContext(typeof(TrainticketBookingDbContext))]
    [Migration("20230620174628_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainticketBooking.Data.Departure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Departures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "ორშაბათი",
                            Destination = "ბათუმი",
                            Source = "თბილისი"
                        });
                });

            modelBuilder.Entity("TrainticketBooking.Data.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PayoutCompleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("TicketId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("TrainticketBooking.Data.Seat", b =>
                {
                    b.Property<Guid>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VagonId")
                        .HasColumnType("int");

                    b.HasKey("SeatId");

                    b.HasIndex("VagonId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            SeatId = new Guid("3cbae06e-2df9-4ec1-b89a-e21c669a12fc"),
                            IsOccupied = false,
                            Number = "1A",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("df24747a-7473-47c4-bb01-03cc16c7bf3d"),
                            IsOccupied = false,
                            Number = "1B",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("5dde3914-2562-4d67-beb3-152a2c6ff3f5"),
                            IsOccupied = false,
                            Number = "1C",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("36b24c41-1abe-4666-a420-357fbf3b9292"),
                            IsOccupied = false,
                            Number = "1D",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("e72a3213-7eb8-49e8-b56c-00d2874b863f"),
                            IsOccupied = false,
                            Number = "2A",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("bb05fff1-1244-4074-9af9-44d7469ae5ba"),
                            IsOccupied = false,
                            Number = "2B",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("174b019e-4f81-47be-a05e-4c31f18bcd0d"),
                            IsOccupied = false,
                            Number = "2C",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("f432c0f8-e338-4187-ae57-b65832603afa"),
                            IsOccupied = false,
                            Number = "2D",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("8dda6be2-fe6e-47e3-95ce-27ca19dbfd2a"),
                            IsOccupied = false,
                            Number = "3A",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("52ce71f2-eb9a-4ff8-a2fb-763035804c8e"),
                            IsOccupied = false,
                            Number = "3B",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("d9d10871-0b92-4c31-ac05-0242d2b94488"),
                            IsOccupied = false,
                            Number = "3C",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("34f4d7d1-4853-4548-8f65-720d47a2157f"),
                            IsOccupied = false,
                            Number = "3D",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("c1a6f484-c8f1-48cb-90f3-68c985acfca1"),
                            IsOccupied = false,
                            Number = "4A",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("3593cc8c-f12e-4aec-a820-d61bf9ce7e19"),
                            IsOccupied = false,
                            Number = "4B",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("8247980c-434f-4a89-b3f2-11d3fe27a784"),
                            IsOccupied = false,
                            Number = "4C",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("6243e5ed-914a-4044-8e34-820aa222bcb7"),
                            IsOccupied = false,
                            Number = "4D",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("9b7464ff-cfae-405e-a507-26b4693c7830"),
                            IsOccupied = false,
                            Number = "5A",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("7f32341b-1548-41dd-90ee-3bc73e7e36f9"),
                            IsOccupied = false,
                            Number = "5B",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("8975417b-7ca6-45a4-9d63-dd4c7894ba37"),
                            IsOccupied = false,
                            Number = "5C",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("d905a55f-7d97-4633-a929-4aa8df003e53"),
                            IsOccupied = false,
                            Number = "5D",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("8a2e724d-adf5-4cce-bbb2-e65c775b04e9"),
                            IsOccupied = false,
                            Number = "6A",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("cf3a12dd-0201-41fc-98cc-b5b8dd02065b"),
                            IsOccupied = false,
                            Number = "6B",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("240f471c-fd3e-42b1-984a-1501e488d3e5"),
                            IsOccupied = false,
                            Number = "6C",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("b981332f-b41d-4b74-ac53-7312b14a2854"),
                            IsOccupied = false,
                            Number = "6D",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("14f3ec0e-b5ff-4338-a890-8fe06bfd1e00"),
                            IsOccupied = false,
                            Number = "7A",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("ba8e6680-0d24-400a-885f-17761f209c2e"),
                            IsOccupied = false,
                            Number = "7B",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("f15cecba-1586-48eb-91f8-3a0afc28f80f"),
                            IsOccupied = false,
                            Number = "7C",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("38754f15-cbac-4f8d-8a89-381dfbf9856a"),
                            IsOccupied = false,
                            Number = "7D",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("6335d17d-ff99-4485-82d2-f4605daa4a09"),
                            IsOccupied = false,
                            Number = "8A",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("a72c1fb4-c5d4-4e72-a950-bc3d46e8b78f"),
                            IsOccupied = false,
                            Number = "8B",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("e398e61d-e570-451f-bcaa-7b65e6fc7e25"),
                            IsOccupied = false,
                            Number = "8C",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("8cf764dc-2fbd-494e-945b-6e90a9a0cbed"),
                            IsOccupied = false,
                            Number = "8D",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("d0f4d8c9-704d-4291-aab3-9d1506bbd1ba"),
                            IsOccupied = false,
                            Number = "9A",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("0e6011e3-a0d8-413e-bb43-4a02766a1708"),
                            IsOccupied = false,
                            Number = "9B",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("f01f917d-3e2f-4d10-8704-d51ef99942c4"),
                            IsOccupied = false,
                            Number = "9C",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("4bc7b9c4-413b-49b8-8b04-f4488085a24e"),
                            IsOccupied = false,
                            Number = "9D",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("fd56616e-ce94-46fd-a6f3-ab72df1cc7af"),
                            IsOccupied = false,
                            Number = "10A",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("98a75295-7d83-4e50-8547-f6df909dc997"),
                            IsOccupied = false,
                            Number = "10B",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("e5aa67c0-e3e1-42d8-9d3d-630ba2dee073"),
                            IsOccupied = false,
                            Number = "10C",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("3e145f13-7536-4955-b33f-cfc3a57395e9"),
                            IsOccupied = false,
                            Number = "10D",
                            Price = 35.00m,
                            VagonId = 1
                        },
                        new
                        {
                            SeatId = new Guid("09446823-dc1a-4195-8097-d6328608af7c"),
                            IsOccupied = false,
                            Number = "1A",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("0af47436-84ef-40a0-9075-d17058a0bfe0"),
                            IsOccupied = false,
                            Number = "1B",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("94b7443a-ec4d-43c0-a47e-0d055e241bc5"),
                            IsOccupied = false,
                            Number = "1C",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("fd4909db-88ca-4fe9-8b95-e1f7ddd8da7e"),
                            IsOccupied = false,
                            Number = "1D",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("c68c2d2d-6b82-49e4-8648-161f0fd3a710"),
                            IsOccupied = false,
                            Number = "2A",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("0a88955f-a854-427d-8a76-43e004700d60"),
                            IsOccupied = false,
                            Number = "2B",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("0c005814-40ee-483c-9405-436a133ba67c"),
                            IsOccupied = false,
                            Number = "2C",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("f26a62ec-ff57-423b-a151-25dcbb3c742b"),
                            IsOccupied = false,
                            Number = "2D",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("3cce4561-0c09-46a1-a642-7e230a92f9f8"),
                            IsOccupied = false,
                            Number = "3A",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("d6976dc9-b0f0-4c23-9ca7-2b709babe94a"),
                            IsOccupied = false,
                            Number = "3B",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("183cf0b1-da77-4515-a120-a8cb25d1513f"),
                            IsOccupied = false,
                            Number = "3C",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("a934b8b7-c54b-4a24-a2a5-dda5f0e9bca3"),
                            IsOccupied = false,
                            Number = "3D",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("60d671fd-6f97-4fa0-b7a6-c01bf77f3736"),
                            IsOccupied = false,
                            Number = "4A",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("1d76a789-d4e9-4c3e-957a-9535418079a1"),
                            IsOccupied = false,
                            Number = "4B",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("d47e4c3c-d50c-47a2-bc0a-07fe522c5a8e"),
                            IsOccupied = false,
                            Number = "4C",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("6b92bf22-2c6b-42e3-97c5-e5f2876a0c21"),
                            IsOccupied = false,
                            Number = "4D",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("f69031b1-e79d-4087-98fa-746c885230b5"),
                            IsOccupied = false,
                            Number = "5A",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("10ca2991-01f6-434f-bcf6-3410445bdd40"),
                            IsOccupied = false,
                            Number = "5B",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("9f5a1ddc-162f-4ad8-a79a-63a1b05116b4"),
                            IsOccupied = false,
                            Number = "5C",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("4c73c0c3-dcb8-4b33-bdfc-2be33d3d645c"),
                            IsOccupied = false,
                            Number = "5D",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("8dd4c9f6-ad64-4307-b61a-63b2b9b9abdc"),
                            IsOccupied = false,
                            Number = "6A",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("f6332e84-7f6c-43b4-96fc-bdcbb7881398"),
                            IsOccupied = false,
                            Number = "6B",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("a9c243e6-af7a-4f40-a1de-e0b80fd58135"),
                            IsOccupied = false,
                            Number = "6C",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("83989daf-89ae-4dc7-9d10-b590c35a1ece"),
                            IsOccupied = false,
                            Number = "6D",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("50562711-2085-4491-bdf8-750eb4650913"),
                            IsOccupied = false,
                            Number = "7A",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("b1a924a2-074b-41c1-9e58-9d21c436ae75"),
                            IsOccupied = false,
                            Number = "7B",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("8b2911c3-695c-4093-a614-5164eb3b08fa"),
                            IsOccupied = false,
                            Number = "7C",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("da464010-0393-4bdc-a40d-eddaf9d955ab"),
                            IsOccupied = false,
                            Number = "7D",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("7a6db1dd-28f3-4995-a59b-0d6a78252021"),
                            IsOccupied = false,
                            Number = "8A",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("84e0a00c-f26a-45c5-bff2-30701aa7855f"),
                            IsOccupied = false,
                            Number = "8B",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("a8061fd3-b700-4317-8f82-297d513677ef"),
                            IsOccupied = false,
                            Number = "8C",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("d26ba4a4-4a77-4d2f-8d95-967b936c9469"),
                            IsOccupied = false,
                            Number = "8D",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("32a92e10-9fa7-4407-ab0b-e5f332847ff3"),
                            IsOccupied = false,
                            Number = "9A",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("77284767-9be4-4d78-95c2-bf38f8195ab0"),
                            IsOccupied = false,
                            Number = "9B",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("7071dc49-a401-468f-9780-ac3ce851b902"),
                            IsOccupied = false,
                            Number = "9C",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("275afcef-3bee-421e-8636-d20d5ba1e885"),
                            IsOccupied = false,
                            Number = "9D",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("b0ea2177-e295-4c58-8d99-1ab8478c0fe4"),
                            IsOccupied = false,
                            Number = "10A",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("157918ac-1ffd-4769-8bc0-f46cbda7a92f"),
                            IsOccupied = false,
                            Number = "10B",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("2a909fcb-07c3-4520-bc0e-bd3b1b6543f9"),
                            IsOccupied = false,
                            Number = "10C",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("559a9366-926d-4289-bfbb-eb3fedd59a23"),
                            IsOccupied = false,
                            Number = "10D",
                            Price = 75.00m,
                            VagonId = 2
                        },
                        new
                        {
                            SeatId = new Guid("a8e1bf74-eab5-4ef6-8431-60f1dbb5fe65"),
                            IsOccupied = false,
                            Number = "1A",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("34b0f59d-994b-43ec-b56b-063a079e0322"),
                            IsOccupied = false,
                            Number = "1B",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("f0a7a440-36fd-479d-ab3b-c039e09a73bd"),
                            IsOccupied = false,
                            Number = "1C",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("0143feef-3530-4cea-a06b-932ebe180b1b"),
                            IsOccupied = false,
                            Number = "1D",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("91bcaf64-baf2-4aac-a191-6ac9a926e1fd"),
                            IsOccupied = false,
                            Number = "2A",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("78fda68d-85ab-4aeb-8925-8cf363402540"),
                            IsOccupied = false,
                            Number = "2B",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("6cd13526-58ab-479f-954c-c6176ada10b2"),
                            IsOccupied = false,
                            Number = "2C",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("61c1bda4-98f7-468d-9d0f-18ae3507b297"),
                            IsOccupied = false,
                            Number = "2D",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("939c2559-9646-4fa5-8c5c-e9248420915c"),
                            IsOccupied = false,
                            Number = "3A",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("1108e302-e63a-4d44-a043-a3baec781ee1"),
                            IsOccupied = false,
                            Number = "3B",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("5bae3403-186c-4fcc-be2e-b5bd6f72568d"),
                            IsOccupied = false,
                            Number = "3C",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("c28069b7-4e81-4b29-b395-41e93b503afa"),
                            IsOccupied = false,
                            Number = "3D",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("6a10f576-64ae-4f5c-b4d2-49d54dd93259"),
                            IsOccupied = false,
                            Number = "4A",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("d77aca44-e724-47f7-86b4-fe7d776b03ae"),
                            IsOccupied = false,
                            Number = "4B",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("c31d50b0-d3ca-40cc-87f5-58581103a9b6"),
                            IsOccupied = false,
                            Number = "4C",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("3248bce4-2a52-4d79-84a1-5e5ed30d397e"),
                            IsOccupied = false,
                            Number = "4D",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("a9b10e02-18f6-4457-9d45-5be8db745d8c"),
                            IsOccupied = false,
                            Number = "5A",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("504c2dd1-c802-4dfe-b818-c839af58297d"),
                            IsOccupied = false,
                            Number = "5B",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("747e5b5a-e374-4c1e-9946-eb6ef56d3402"),
                            IsOccupied = false,
                            Number = "5C",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("175602b2-cee8-44d9-aa64-920331313a42"),
                            IsOccupied = false,
                            Number = "5D",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("677c414c-dd85-49ac-9d6e-fb33c5eb769f"),
                            IsOccupied = false,
                            Number = "6A",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("0b3f1ee2-b282-4c24-8dcb-d5ca9927ddb1"),
                            IsOccupied = false,
                            Number = "6B",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("3fa055ea-564c-4176-8cc1-dedb007ee3d4"),
                            IsOccupied = false,
                            Number = "6C",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("b92b6f95-b70f-428d-9785-4b38147e9ed8"),
                            IsOccupied = false,
                            Number = "6D",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("ecf72c4e-3981-45f7-b12c-f5227550c494"),
                            IsOccupied = false,
                            Number = "7A",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("b8d28a2f-0377-4ef9-b32e-8edaf956fa41"),
                            IsOccupied = false,
                            Number = "7B",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("d4d5cd0b-91ac-42f6-917e-993d3fee58b4"),
                            IsOccupied = false,
                            Number = "7C",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("892ee038-b01b-4ef4-a28b-eaea843136e5"),
                            IsOccupied = false,
                            Number = "7D",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("1dd35bdd-b42d-4042-9471-02aa29b882cc"),
                            IsOccupied = false,
                            Number = "8A",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("dc8f40b7-0341-4ecf-b754-8b77d8c4d292"),
                            IsOccupied = false,
                            Number = "8B",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("7f5c0b96-466a-4e10-90e3-e310c7eeb80d"),
                            IsOccupied = false,
                            Number = "8C",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("2adb2415-7a77-4c2a-944a-71f1100fe540"),
                            IsOccupied = false,
                            Number = "8D",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("4c0cfdfd-1167-4901-b657-689df21a0139"),
                            IsOccupied = false,
                            Number = "9A",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("656b3a22-9196-43c9-bd42-5d8fd76a9bf6"),
                            IsOccupied = false,
                            Number = "9B",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("a4149da3-dc40-4e18-bbe8-b71f33526e69"),
                            IsOccupied = false,
                            Number = "9C",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("00359150-e45d-4846-a19f-6437977639ec"),
                            IsOccupied = false,
                            Number = "9D",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("b01c97bd-7fbd-4acb-a832-bbe9b16f7808"),
                            IsOccupied = false,
                            Number = "10A",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("18a7d767-2f06-4408-a8d5-e86df786d6c4"),
                            IsOccupied = false,
                            Number = "10B",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("afec5569-f66e-4cc3-821b-267541c8f3aa"),
                            IsOccupied = false,
                            Number = "10C",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("9e42fe5a-0444-4979-b577-646398521d0e"),
                            IsOccupied = false,
                            Number = "10D",
                            Price = 125.00m,
                            VagonId = 3
                        },
                        new
                        {
                            SeatId = new Guid("68af96f0-9ccf-49dc-9afc-46d1e358bc31"),
                            IsOccupied = false,
                            Number = "1A",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("2d04d75c-e969-4d4b-83af-a2c71f8488b8"),
                            IsOccupied = false,
                            Number = "1B",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("8c29f62e-110f-4d50-bff8-698f48f4b297"),
                            IsOccupied = false,
                            Number = "1C",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("c551913b-a714-4bbd-b332-0b1a6b0c952a"),
                            IsOccupied = false,
                            Number = "1D",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("85c18bca-70f8-4b80-ae2d-67449c68cd97"),
                            IsOccupied = false,
                            Number = "2A",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("232c247f-9ea5-45dc-85f8-b5fb952960f8"),
                            IsOccupied = false,
                            Number = "2B",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("4c94b6c1-f2fc-4af0-967d-83d7af5cc267"),
                            IsOccupied = false,
                            Number = "2C",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("60666b5b-917a-40bf-b8bc-1124f180d717"),
                            IsOccupied = false,
                            Number = "2D",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("0ae38f8d-028c-4f3b-abfd-10d987bb6944"),
                            IsOccupied = false,
                            Number = "3A",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("051e0418-472c-4e63-b801-c136b6eb3f89"),
                            IsOccupied = false,
                            Number = "3B",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("580ff731-c5ec-4f1d-97de-b4f47a97a86f"),
                            IsOccupied = false,
                            Number = "3C",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("262b926b-a06f-4781-afb9-28206f99d6ed"),
                            IsOccupied = false,
                            Number = "3D",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("445d6f53-3910-4c37-b548-a9e38190398e"),
                            IsOccupied = false,
                            Number = "4A",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("7a40162a-f8b0-48ac-8d1f-cd3305776f86"),
                            IsOccupied = false,
                            Number = "4B",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("df06fab2-c0b2-4cc1-970e-67821ecd6c70"),
                            IsOccupied = false,
                            Number = "4C",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("215fd5ee-668d-4227-81b0-73529804a215"),
                            IsOccupied = false,
                            Number = "4D",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("676ab2fa-8306-408d-a515-13c0b4531066"),
                            IsOccupied = false,
                            Number = "5A",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("74351140-d59a-48a1-a15b-73b6dfdf02ab"),
                            IsOccupied = false,
                            Number = "5B",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("53c20933-5ae4-4fd8-a0f4-16765d827a1f"),
                            IsOccupied = false,
                            Number = "5C",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("c7c0aa75-a3fd-4f0a-a2bb-fde781356be1"),
                            IsOccupied = false,
                            Number = "5D",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("abc874bf-4f18-4908-a0b6-55a7c7182631"),
                            IsOccupied = false,
                            Number = "6A",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("63653fc0-6c76-4628-9e0d-b0fa2e155773"),
                            IsOccupied = false,
                            Number = "6B",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("72774466-dc6d-4e8a-9d00-6df14d3420e7"),
                            IsOccupied = false,
                            Number = "6C",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("d02dfc94-e8b7-400f-95ec-b76ceab73e4c"),
                            IsOccupied = false,
                            Number = "6D",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("95e07e42-8f4e-464f-ba0d-030a2d8427d1"),
                            IsOccupied = false,
                            Number = "7A",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("83f642fb-d1ae-4f2d-b880-58bc86abe1dd"),
                            IsOccupied = false,
                            Number = "7B",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("947870bc-3fe7-481b-951c-8fecf8c91742"),
                            IsOccupied = false,
                            Number = "7C",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("0823f441-21fd-4bca-8497-95ec900731ca"),
                            IsOccupied = false,
                            Number = "7D",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("1e11fe82-b350-4065-ab13-8bc33abf3b1e"),
                            IsOccupied = false,
                            Number = "8A",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("312012e2-2d3a-494c-9326-d276cc400fa8"),
                            IsOccupied = false,
                            Number = "8B",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("6ee9631e-49ee-486b-91f0-f714b587f51b"),
                            IsOccupied = false,
                            Number = "8C",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("7bf76eec-04c6-48ed-b382-7e775e1628c3"),
                            IsOccupied = false,
                            Number = "8D",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("799b9219-1e30-4f86-9883-88022d75d249"),
                            IsOccupied = false,
                            Number = "9A",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("205b8241-515c-444c-b55d-21bd17197ada"),
                            IsOccupied = false,
                            Number = "9B",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("fa53ef20-74f9-4b80-b7af-1a38075a8193"),
                            IsOccupied = false,
                            Number = "9C",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("65950804-3741-49db-bda7-ebf699289ca8"),
                            IsOccupied = false,
                            Number = "9D",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("152031c7-f93a-485f-8952-2ca40217d8d8"),
                            IsOccupied = false,
                            Number = "10A",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("b13f2e6c-5eb4-46a3-855e-b15b5a9e9572"),
                            IsOccupied = false,
                            Number = "10B",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("40525987-6ac9-414e-a3bf-bc47dfe068f7"),
                            IsOccupied = false,
                            Number = "10C",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("4a63c1be-acb7-49a8-8c06-e3b4cb855c19"),
                            IsOccupied = false,
                            Number = "10D",
                            Price = 35.00m,
                            VagonId = 4
                        },
                        new
                        {
                            SeatId = new Guid("f812ab6b-ff23-4cc2-92ec-6ee6a65a593e"),
                            IsOccupied = false,
                            Number = "1A",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("517460c6-2a13-4cfa-80bb-fbf3c0970446"),
                            IsOccupied = false,
                            Number = "1B",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("cbcee5db-f169-47fb-82a8-f2b10bf597cb"),
                            IsOccupied = false,
                            Number = "1C",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("4c32a31e-93e9-49e2-82cd-65c66a6edc4b"),
                            IsOccupied = false,
                            Number = "1D",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("0e3c3b88-a5c7-4f0c-a7aa-7082838b8d22"),
                            IsOccupied = false,
                            Number = "2A",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("ad01fed4-168a-42bc-a5c7-74166abb0296"),
                            IsOccupied = false,
                            Number = "2B",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("ff964064-18aa-439a-9df0-a59e0c3bf239"),
                            IsOccupied = false,
                            Number = "2C",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("13ed9453-8749-47e9-bbad-5ef190f88137"),
                            IsOccupied = false,
                            Number = "2D",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("b321052d-682c-4b41-b1c3-08c4156b76cd"),
                            IsOccupied = false,
                            Number = "3A",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("97b04e7c-ef86-40ff-a01c-4ed7cbefbbb9"),
                            IsOccupied = false,
                            Number = "3B",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("04e9bb12-4cf8-4302-97c8-c84ea3611985"),
                            IsOccupied = false,
                            Number = "3C",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("744fc20d-8652-4092-930e-2cb57d9e5750"),
                            IsOccupied = false,
                            Number = "3D",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("a717674d-65b0-4ba1-a770-8bc6257235bb"),
                            IsOccupied = false,
                            Number = "4A",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("a2f41b17-1aaa-442c-be25-14ea6adff0fc"),
                            IsOccupied = false,
                            Number = "4B",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("808db548-30bc-4b6a-a547-de138d0a1847"),
                            IsOccupied = false,
                            Number = "4C",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("371fc749-f479-474a-92f0-c72a0105fdd3"),
                            IsOccupied = false,
                            Number = "4D",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("8d3d013d-e1a7-47e5-adcb-a221c3358331"),
                            IsOccupied = false,
                            Number = "5A",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("8d4f9845-046e-41da-b1d5-67ddf335dfae"),
                            IsOccupied = false,
                            Number = "5B",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("4b34eb2b-8f05-43d5-afbe-09e5aa8c28f6"),
                            IsOccupied = false,
                            Number = "5C",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("8b2fe303-854b-4bc7-ab9a-a24a67080627"),
                            IsOccupied = false,
                            Number = "5D",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("1ccb80e6-8e75-44ab-b389-70c17647f051"),
                            IsOccupied = false,
                            Number = "6A",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("d38b2970-203d-4efe-af71-c5f6c734541f"),
                            IsOccupied = false,
                            Number = "6B",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("c6bf5c76-2eec-4a87-b1d8-2859d610f32d"),
                            IsOccupied = false,
                            Number = "6C",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("92629395-885c-4d77-9627-e802ff5185a3"),
                            IsOccupied = false,
                            Number = "6D",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("f4399942-34d0-4420-a1a4-3c9ba6b8d147"),
                            IsOccupied = false,
                            Number = "7A",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("27b4a3a9-0f09-47e1-9b95-eea1982e4e73"),
                            IsOccupied = false,
                            Number = "7B",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("56c23a80-9852-47fa-a9d7-b6d1289a98c9"),
                            IsOccupied = false,
                            Number = "7C",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("d9c2d186-d8d5-42d0-a57d-6b1568d5b792"),
                            IsOccupied = false,
                            Number = "7D",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("2546c1dc-8e6f-4a97-b81f-26e35c74a893"),
                            IsOccupied = false,
                            Number = "8A",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("b173209f-7f6a-446d-bb2d-957720329470"),
                            IsOccupied = false,
                            Number = "8B",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("ff608396-733f-4b02-a124-0d563905c500"),
                            IsOccupied = false,
                            Number = "8C",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("38feee89-6ca9-48aa-9ae5-c1b33e245524"),
                            IsOccupied = false,
                            Number = "8D",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("24cef2d2-5127-4285-8487-053089435846"),
                            IsOccupied = false,
                            Number = "9A",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("e5bc61af-19bb-4020-8a41-95ef180987b3"),
                            IsOccupied = false,
                            Number = "9B",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("3aa0dcf7-7bfc-4681-8bb7-ca6da053a218"),
                            IsOccupied = false,
                            Number = "9C",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("7376b1a1-d9f6-40d1-80f5-a6eb3968d52a"),
                            IsOccupied = false,
                            Number = "9D",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("0a7fc176-da91-421f-ac45-1bd07d580f96"),
                            IsOccupied = false,
                            Number = "10A",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("00f2516e-2037-4596-a0a2-c57bc90d8d71"),
                            IsOccupied = false,
                            Number = "10B",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("4f6362ba-c1a8-4856-bad6-5caaeee41fbb"),
                            IsOccupied = false,
                            Number = "10C",
                            Price = 35.00m,
                            VagonId = 5
                        },
                        new
                        {
                            SeatId = new Guid("a58feb51-1162-434a-8966-a36eeb0bea12"),
                            IsOccupied = false,
                            Number = "10D",
                            Price = 35.00m,
                            VagonId = 5
                        });
                });

            modelBuilder.Entity("TrainticketBooking.Data.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb1ccab2-a8e5-4fec-b640-90f76e7338ab"),
                            Name = "თბილისი",
                            StationNumber = "56014"
                        },
                        new
                        {
                            Id = new Guid("9d6a972f-028d-4af9-89e4-9a2ecc75b1a2"),
                            Name = "ბათუმი",
                            StationNumber = "57151"
                        },
                        new
                        {
                            Id = new Guid("14e9c3f3-aa64-44cf-bf1c-2f0da56c2dca"),
                            Name = "ზუგდიდი",
                            StationNumber = "57290"
                        },
                        new
                        {
                            Id = new Guid("d0b2558c-7362-402b-9d60-9fcd51c80436"),
                            Name = "ფოთი",
                            StationNumber = "57210"
                        },
                        new
                        {
                            Id = new Guid("f847108f-d96c-452e-8f86-2f7ff8d04376"),
                            Name = "ქობულეთი",
                            StationNumber = "57120"
                        },
                        new
                        {
                            Id = new Guid("b53fce52-1bbe-4474-9158-1ac9fcea6897"),
                            Name = "ურეკი",
                            StationNumber = "57070"
                        },
                        new
                        {
                            Id = new Guid("41624cf2-1a30-4122-b451-ff56ce4a7c75"),
                            Name = "აბაშა",
                            StationNumber = "57170"
                        },
                        new
                        {
                            Id = new Guid("2094d00c-7cce-4c47-a69e-32a5930c8282"),
                            Name = "ქუთაისი I",
                            StationNumber = "57530"
                        },
                        new
                        {
                            Id = new Guid("9d768d5c-ed8b-498d-9a7e-21dd88f8f874"),
                            Name = "ბორჯომი",
                            StationNumber = "57760"
                        });
                });

            modelBuilder.Entity("TrainticketBooking.Data.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrainID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TrainticketBooking.Data.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Arrive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("From")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("To")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("From");

                    b.ToTable("Trains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Arrive = "05:47",
                            Date = "ორშაბათი",
                            Departure = "00:35",
                            From = "თბილისი",
                            Number = 812,
                            To = "ბათუმი"
                        },
                        new
                        {
                            Id = 2,
                            Arrive = "15:38",
                            Date = "ორშაბათი",
                            Departure = "10:25",
                            From = "თბილისი",
                            Number = 808,
                            To = "ბათუმი"
                        },
                        new
                        {
                            Id = 3,
                            Arrive = "22:17",
                            Date = "ორშაბათი",
                            Departure = "17:05",
                            From = "თბილისი",
                            Number = 804,
                            To = "ბათუმი"
                        });
                });

            modelBuilder.Entity("TrainticketBooking.Data.Vagon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.Property<int>("TrainNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainId");

                    b.ToTable("Vagons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "II კლასი",
                            TrainId = 1,
                            TrainNumber = 812
                        },
                        new
                        {
                            Id = 2,
                            Name = "I კლასი",
                            TrainId = 1,
                            TrainNumber = 812
                        },
                        new
                        {
                            Id = 3,
                            Name = "ბიზნესი",
                            TrainId = 1,
                            TrainNumber = 812
                        },
                        new
                        {
                            Id = 4,
                            Name = "II კლასი",
                            TrainId = 2,
                            TrainNumber = 808
                        },
                        new
                        {
                            Id = 5,
                            Name = "II კლასი",
                            TrainId = 2,
                            TrainNumber = 804
                        });
                });

            modelBuilder.Entity("TrainticketBooking.Data.Person", b =>
                {
                    b.HasOne("TrainticketBooking.Data.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId");

                    b.HasOne("TrainticketBooking.Data.Ticket", null)
                        .WithMany("Persons")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("TrainticketBooking.Data.Seat", b =>
                {
                    b.HasOne("TrainticketBooking.Data.Vagon", null)
                        .WithMany("Seats")
                        .HasForeignKey("VagonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainticketBooking.Data.Ticket", b =>
                {
                    b.HasOne("TrainticketBooking.Data.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("TrainticketBooking.Data.Train", b =>
                {
                    b.HasOne("TrainticketBooking.Data.Departure", null)
                        .WithMany("Trains")
                        .HasForeignKey("From")
                        .HasPrincipalKey("Source");
                });

            modelBuilder.Entity("TrainticketBooking.Data.Vagon", b =>
                {
                    b.HasOne("TrainticketBooking.Data.Train", null)
                        .WithMany("Vagons")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainticketBooking.Data.Departure", b =>
                {
                    b.Navigation("Trains");
                });

            modelBuilder.Entity("TrainticketBooking.Data.Ticket", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("TrainticketBooking.Data.Train", b =>
                {
                    b.Navigation("Vagons");
                });

            modelBuilder.Entity("TrainticketBooking.Data.Vagon", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
